const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// MongoDB Connection
mongoose.connect('mongodb://localhost:27017/tarotdb')
.then(() => console.log('Connected to MongoDB'))
.catch((err) => console.error('MongoDB connection error:', err));

// Tarot Card Schema
const tarotSchema = new mongoose.Schema({
  name: { type: String, required: true },
  number: { type: Number, required: true },
  arcana: { type: String, enum: ['Major', 'Minor'], required: true },
  suit: { type: String, enum: ['Wands', 'Cups', 'Swords', 'Pentacles', null] },
  uprightMeaning: { type: String, required: true },
  reversedMeaning: { type: String, required: true },
  symbolism: { type: [String], required: true },
  numerology: { type: String, required: true },
  keywords: { type: [String], required: true },
  description: { type: String, required: true },
  advice: { type: String, required: true },
});

const TarotCard = mongoose.model('TarotCard', tarotSchema);

// Sample Data for All 78 Tarot Cards
    
  const cards = [
    // Major Arcana (0-21)
    {
      name: 'The Fool',
      number: 0,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'New beginnings, adventure, and embracing the unknown with optimism.',
      reversedMeaning: 'Recklessness, fear of change, or hesitation holding you back.',
      symbolism: ['Dog: Loyalty and protection', 'Cliff: Leap of faith', 'Sun: Hope and purity'],
      numerology: '0 represents infinite potential and the start of a journey.',
      keywords: ['Beginnings', 'Innocence', 'Spontaneity', 'Freedom'],
      description: 'The Fool depicts a youthful figure standing at the edge of a cliff, ready to embark on a new journey with a sense of wonder and openness.',
      advice: 'Trust your instincts and take a leap of faith, but stay mindful of risks.',
    },
    {
      name: 'The Magician',
      number: 1,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Manifestation, resourcefulness, and using your skills to create.',
      reversedMeaning: 'Manipulation, untapped potential, or lack of focus.',
      symbolism: ['Wand: Power and direction', 'Infinity Symbol: Limitless possibilities', 'Tools: Mastery of elements'],
      numerology: '1 signifies initiative, leadership, and new starts.',
      keywords: ['Manifestation', 'Skill', 'Willpower', 'Creativity'],
      description: 'The Magician stands with tools of all suits, channeling energy to turn ideas into reality.',
      advice: 'Focus your energy and use your talents to achieve your goals.',
    },
    {
      name: 'The High Priestess',
      number: 2,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Intuition, mystery, and inner wisdom guiding you.',
      reversedMeaning: 'Secrets, blocked intuition, or ignoring inner voice.',
      symbolism: ['Moon: Intuition', 'Pomegranates: Fertility and mystery', 'Scroll: Hidden knowledge'],
      numerology: '2 represents balance, duality, and intuition.',
      keywords: ['Intuition', 'Mystery', 'Wisdom', 'Subconscious'],
      description: 'The High Priestess sits between pillars, guarding the mysteries of the subconscious.',
      advice: 'Listen to your inner voice and trust your gut feelings.',
    },
    {
      name: 'The Empress',
      number: 3,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Abundance, nurturing, and creative growth.',
      reversedMeaning: 'Neglect, creative blocks, or over-dependence.',
      symbolism: ['Wheat: Fertility', 'Scepter: Authority', 'Nature: Growth and nurturing'],
      numerology: '3 symbolizes creativity, growth, and expression.',
      keywords: ['Nurturing', 'Abundance', 'Creativity', 'Fertility'],
      description: 'The Empress sits in a lush field, embodying fertility and the power of creation.',
      advice: 'Embrace your creative side and nurture yourself and others.',
    },
    {
      name: 'The Emperor',
      number: 4,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Authority, structure, and disciplined leadership.',
      reversedMeaning: 'Rigidity, control issues, or lack of discipline.',
      symbolism: ['Throne: Authority', 'Ram: Determination', 'Scepter: Power'],
      numerology: '4 represents stability, structure, and foundation.',
      keywords: ['Authority', 'Structure', 'Control', 'Leadership'],
      description: 'The Emperor sits on a throne, representing order and control over chaos.',
      advice: 'Establish boundaries and take charge with confidence.',
    },
    {
      name: 'The Hierophant',
      number: 5,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Tradition, spiritual guidance, and moral values.',
      reversedMeaning: 'Conformity, rebellion, or questioning beliefs.',
      symbolism: ['Keys: Knowledge', 'Staff: Spiritual authority', 'Pillars: Duality'],
      numerology: '5 signifies change, learning, and spiritual growth.',
      keywords: ['Tradition', 'Spirituality', 'Guidance', 'Conformity'],
      description: 'The Hierophant teaches spiritual wisdom, guiding others through tradition.',
      advice: 'Seek guidance from trusted sources or share your wisdom.',
    },
    {
      name: 'The Lovers',
      number: 6,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Love, harmony, and important choices.',
      reversedMeaning: 'Disharmony, imbalance, or misaligned values.',
      symbolism: ['Angel: Divine guidance', 'Tree: Knowledge', 'Couple: Union'],
      numerology: '6 represents harmony, love, and balance.',
      keywords: ['Love', 'Choice', 'Harmony', 'Union'],
      description: 'The Lovers depict a couple under an angel, symbolizing deep connections and choices.',
      advice: 'Align your choices with your values and heart.',
    },
    {
      name: 'The Chariot',
      number: 7,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Determination, willpower, and victory through focus.',
      reversedMeaning: 'Lack of direction, aggression, or scattered energy.',
      symbolism: ['Chariot: Control', 'Sphinxes: Opposing forces', 'Stars: Guidance'],
      numerology: '7 symbolizes spiritual insight and determination.',
      keywords: ['Willpower', 'Control', 'Victory', 'Determination'],
      description: 'The Chariot shows a warrior driving forward, mastering opposing forces.',
      advice: 'Stay focused and harness your energy to achieve your goals.',
    },
    {
      name: 'Strength',
      number: 8,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Inner strength, courage, and compassion.',
      reversedMeaning: 'Self-doubt, weakness, or suppressed emotions.',
      symbolism: ['Lion: Courage', 'Infinity Symbol: Endless strength', 'Woman: Compassion'],
      numerology: '8 represents power, balance, and resilience.',
      keywords: ['Strength', 'Courage', 'Compassion', 'Resilience'],
      description: 'A woman tames a lion, showing strength through gentle control.',
      advice: 'Tap into your inner courage and approach challenges with kindness.',
    },
    {
      name: 'The Hermit',
      number: 9,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Introspection, solitude, and seeking inner truth.',
      reversedMeaning: 'Isolation, withdrawal, or loneliness.',
      symbolism: ['Lantern: Inner light', 'Staff: Stability', 'Mountain: Spiritual ascent'],
      numerology: '9 signifies wisdom, completion, and introspection.',
      keywords: ['Solitude', 'Introspection', 'Wisdom', 'Guidance'],
      description: 'The Hermit stands alone, illuminating the path with inner wisdom.',
      advice: 'Take time for reflection to find clarity and truth.',
    },
    {
      name: 'Wheel of Fortune',
      number: 10,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Cycles, luck, and destiny unfolding.',
      reversedMeaning: 'Bad luck, resistance to change, or setbacks.',
      symbolism: ['Wheel: Cycles', 'Sphinx: Fate', 'Four Creatures: Elements'],
      numerology: '10 represents completion and new cycles.',
      keywords: ['Luck', 'Cycles', 'Destiny', 'Change'],
      description: 'The Wheel spins, bringing change and opportunities guided by fate.',
      advice: 'Embrace change and trust the flow of life.',
    },
    {
      name: 'Justice',
      number: 11,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Fairness, truth, and accountability.',
      reversedMeaning: 'Injustice, dishonesty, or imbalance.',
      symbolism: ['Scales: Balance', 'Sword: Truth', 'Pillars: Stability'],
      numerology: '11 symbolizes justice, intuition, and spiritual insight.',
      keywords: ['Justice', 'Truth', 'Balance', 'Accountability'],
      description: 'Justice holds scales and a sword, representing fairness and truth.',
      advice: 'Seek truth and make decisions with integrity.',
    },
    {
      name: 'The Hanged Man',
      number: 12,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Surrender, sacrifice, and new perspectives.',
      reversedMeaning: 'Stagnation, resistance, or delayed decisions.',
      symbolism: ['Halo: Enlightenment', 'Tree: Sacrifice', 'Hanging: Suspension'],
      numerology: '12 represents surrender and spiritual growth.',
      keywords: ['Surrender', 'Sacrifice', 'Perspective', 'Patience'],
      description: 'The Hanged Man hangs upside down, gaining insight through surrender.',
      advice: 'Let go and view challenges from a new angle.',
    },
    {
      name: 'Death',
      number: 13,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Transformation, endings, and new beginnings.',
      reversedMeaning: 'Resistance to change, stagnation, or fear of loss.',
      symbolism: ['Skeleton: Endings', 'Sun: Rebirth', 'Horse: Transition'],
      numerology: '13 signifies transformation and renewal.',
      keywords: ['Transformation', 'Endings', 'Rebirth', 'Change'],
      description: 'Death rides a horse, symbolizing inevitable change and renewal.',
      advice: 'Embrace change as a path to growth and renewal.',
    },
    {
      name: 'Temperance',
      number: 14,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Balance, moderation, and harmony.',
      reversedMeaning: 'Imbalance, excess, or lack of harmony.',
      symbolism: ['Cups: Balance', 'Wings: Divinity', 'Path: Moderation'],
      numerology: '14 represents balance and adaptation.',
      keywords: ['Balance', 'Moderation', 'Harmony', 'Patience'],
      description: 'An angel blends water between cups, symbolizing harmony and balance.',
      advice: 'Find balance and practice patience in your actions.',
    },
    {
      name: 'The Devil',
      number: 15,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Temptation, bondage, or materialism.',
      reversedMeaning: 'Freedom, breaking free, or overcoming addiction.',
      symbolism: ['Chains: Bondage', 'Horns: Temptation', 'Torch: Illumination'],
      numerology: '15 signifies materialism and liberation.',
      keywords: ['Temptation', 'Bondage', 'Materialism', 'Freedom'],
      description: 'The Devil looms over chained figures, representing entrapment by desires.',
      advice: 'Recognize and break free from unhealthy patterns.',
    },
    {
      name: 'The Tower',
      number: 16,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Sudden change, upheaval, or revelation.',
      reversedMeaning: 'Fear of change, avoiding disaster, or delayed upheaval.',
      symbolism: ['Lightning: Sudden change', 'Tower: Destruction', 'Falling Figures: Upheaval'],
      numerology: '16 represents sudden change and awakening.',
      keywords: ['Upheaval', 'Change', 'Revelation', 'Destruction'],
      description: 'A tower is struck by lightning, symbolizing sudden, transformative change.',
      advice: 'Embrace upheaval as a chance for growth and rebuilding.',
    },
    {
      name: 'The Star',
      number: 17,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Hope, inspiration, and spiritual guidance.',
      reversedMeaning: 'Hopelessness, lack of faith, or disconnection.',
      symbolism: ['Stars: Hope', 'Water: Healing', 'Woman: Inspiration'],
      numerology: '17 signifies hope and spiritual insight.',
      keywords: ['Hope', 'Inspiration', 'Healing', 'Faith'],
      description: 'A woman pours water under stars, symbolizing hope and renewal.',
      advice: 'Trust in the universe and let hope guide you forward.',
    },
    {
      name: 'The Moon',
      number: 18,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Illusion, intuition, and the subconscious.',
      reversedMeaning: 'Confusion, fear, or suppressed emotions.',
      symbolism: ['Moon: Intuition', 'Wolf: Instinct', 'Path: Uncertainty'],
      numerology: '18 represents mystery and intuition.',
      keywords: ['Illusion', 'Intuition', 'Subconscious', 'Fear'],
      description: 'The Moon illuminates a path, revealing hidden truths and instincts.',
      advice: 'Trust your intuition to navigate uncertainty.',
    },
    {
      name: 'The Sun',
      number: 19,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Joy, success, and vitality.',
      reversedMeaning: 'Lack of clarity, temporary setbacks, or low energy.',
      symbolism: ['Sun: Vitality', 'Child: Innocence', 'Sunflowers: Positivity'],
      numerology: '19 signifies success and enlightenment.',
      keywords: ['Joy', 'Success', 'Vitality', 'Clarity'],
      description: 'A child rides under a bright sun, radiating joy and success.',
      advice: 'Embrace positivity and let your inner light shine.',
    },
    {
      name: 'Judgement',
      number: 20,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Awakening, renewal, and self-evaluation.',
      reversedMeaning: 'Self-doubt, denial, or fear of change.',
      symbolism: ['Angel: Awakening', 'Trumpet: Call to action', 'Figures: Rebirth'],
      numerology: '20 represents renewal and transformation.',
      keywords: ['Awakening', 'Renewal', 'Judgment', 'Transformation'],
      description: 'An angel calls figures to rise, symbolizing a spiritual awakening.',
      advice: 'Reflect on your path and embrace transformation.',
    },
    {
      name: 'The World',
      number: 21,
      arcana: 'Major',
      suit: null,
      uprightMeaning: 'Completion, fulfillment, and unity.',
      reversedMeaning: 'Incompletion, delays, or lack of closure.',
      symbolism: ['Wreath: Completion', 'Four Figures: Elements', 'Dancer: Unity'],
      numerology: '21 signifies fulfillment and wholeness.',
      keywords: ['Completion', 'Fulfillment', 'Unity', 'Success'],
      description: 'A dancer within a wreath celebrates the completion of a cycle.',
      advice: 'Celebrate your achievements and embrace new beginnings.',
    },
    // Minor Arcana: Wands
    {
      name: 'Ace of Wands',
      number: 1,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Inspiration, new opportunities, and creative energy.',
      reversedMeaning: 'Delays, lack of passion, or missed opportunities.',
      symbolism: ['Wand: Creativity', 'Hand: Opportunity', 'Sprouts: Growth'],
      numerology: '1 signifies new beginnings and initiative.',
      keywords: ['Inspiration', 'Creativity', 'Energy', 'Opportunity'],
      description: 'A hand holds a sprouting wand, symbolizing creative potential.',
      advice: 'Seize new opportunities and channel your passion.',
    },
    {
      name: 'Two of Wands',
      number: 2,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Planning, decisions, and bold ambition.',
      reversedMeaning: 'Fear of change, indecision, or lack of planning.',
      symbolism: ['Globe: Ambition', 'Wands: Choices', 'Horizon: Future'],
      numerology: '2 represents choices and balance.',
      keywords: ['Planning', 'Ambition', 'Decisions', 'Vision'],
      description: 'A figure holds a globe, contemplating future possibilities.',
      advice: 'Plan carefully and trust your vision for the future.',
    },
    {
      name: 'Three of Wands',
      number: 3,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Expansion, foresight, and progress.',
      reversedMeaning: 'Delays, obstacles, or lack of foresight.',
      symbolism: ['Ships: Opportunities', 'Wands: Stability', 'Horizon: Growth'],
      numerology: '3 symbolizes creativity and expansion.',
      keywords: ['Expansion', 'Foresight', 'Progress', 'Opportunity'],
      description: 'A figure watches ships, awaiting the fruits of their efforts.',
      advice: 'Stay patient and keep your eyes on long-term goals.',
    },
    {
      name: 'Four of Wands',
      number: 4,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Celebration, stability, and community.',
      reversedMeaning: 'Tension, lack of harmony, or instability.',
      symbolism: ['Canopy: Celebration', 'Wands: Stability', 'Flowers: Joy'],
      numerology: '4 represents stability and foundation.',
      keywords: ['Celebration', 'Stability', 'Community', 'Joy'],
      description: 'A joyful gathering under a canopy, celebrating milestones.',
      advice: 'Celebrate your achievements and strengthen community ties.',
    },
    {
      name: 'Five of Wands',
      number: 5,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Conflict, competition, or creative tension.',
      reversedMeaning: 'Resolution, harmony, or avoiding conflict.',
      symbolism: ['Wands: Struggle', 'Figures: Competition', 'Chaos: Tension'],
      numerology: '5 signifies change and conflict.',
      keywords: ['Conflict', 'Competition', 'Tension', 'Challenge'],
      description: 'Figures clash with wands, representing creative or competitive struggles.',
      advice: 'Embrace healthy competition and find constructive solutions.',
    },
    {
      name: 'Six of Wands',
      number: 6,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Victory, recognition, and public success.',
      reversedMeaning: 'Ego, setbacks, or lack of recognition.',
      symbolism: ['Laurel: Victory', 'Horse: Triumph', 'Crowd: Recognition'],
      numerology: '6 represents harmony and success.',
      keywords: ['Victory', 'Recognition', 'Success', 'Pride'],
      description: 'A rider is celebrated, symbolizing triumph and recognition.',
      advice: 'Own your success but stay humble and grateful.',
    },
    {
      name: 'Seven of Wands',
      number: 7,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Defense, standing your ground, and perseverance.',
      reversedMeaning: 'Overwhelm, giving up, or lack of confidence.',
      symbolism: ['High Ground: Advantage', 'Wands: Opposition', 'Figure: Defense'],
      numerology: '7 symbolizes resilience and determination.',
      keywords: ['Defense', 'Perseverance', 'Courage', 'Challenge'],
      description: 'A figure defends their position against opposition.',
      advice: 'Stand firm in your beliefs and protect your progress.',
    },
    {
      name: 'Eight of Wands',
      number: 8,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Speed, movement, and swift progress.',
      reversedMeaning: 'Delays, frustration, or scattered energy.',
      symbolism: ['Wands: Motion', 'Sky: Speed', 'Landscape: Progress'],
      numerology: '8 represents momentum and energy.',
      keywords: ['Speed', 'Progress', 'Movement', 'Action'],
      description: 'Wands fly through the air, symbolizing rapid progress.',
      advice: 'Act quickly and seize the momentum.',
    },
    {
      name: 'Nine of Wands',
      number: 9,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Resilience, persistence, and guarding your progress.',
      reversedMeaning: 'Exhaustion, defensiveness, or giving up.',
      symbolism: ['Wands: Barriers', 'Figure: Resilience', 'Bandage: Wounds'],
      numerology: '9 signifies persistence and nearing completion.',
      keywords: ['Resilience', 'Persistence', 'Defense', 'Strength'],
      description: 'A weary figure stands guard, resilient despite challenges.',
      advice: 'Stay strong and protect your achievements.',
    },
    {
      name: 'Ten of Wands',
      number: 10,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Burden, responsibility, or overworking.',
      reversedMeaning: 'Releasing burdens, delegation, or burnout.',
      symbolism: ['Wands: Burden', 'Figure: Struggle', 'Village: Goal'],
      numerology: '10 represents completion and overload.',
      keywords: ['Burden', 'Responsibility', 'Effort', 'Overload'],
      description: 'A figure carries a heavy load of wands, nearing their goal.',
      advice: 'Delegate tasks and avoid taking on too much.',
    },
    {
      name: 'Page of Wands',
      number: 11,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Enthusiasm, exploration, and new ideas.',
      reversedMeaning: 'Immaturity, lack of direction, or recklessness.',
      symbolism: ['Wand: Inspiration', 'Desert: Exploration', 'Page: Youthful energy'],
      numerology: '11 signifies intuition and new beginnings.',
      keywords: ['Enthusiasm', 'Exploration', 'Ideas', 'Energy'],
      description: 'A page holds a wand, eager to explore new possibilities.',
      advice: 'Embrace your curiosity and pursue new ideas with enthusiasm.',
    },
    {
      name: 'Knight of Wands',
      number: 12,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Adventure, passion, and bold action.',
      reversedMeaning: 'Impulsiveness, recklessness, or scattered energy.',
      symbolism: ['Horse: Action', 'Wand: Passion', 'Armor: Courage'],
      numerology: '12 represents dynamic energy and pursuit.',
      keywords: ['Adventure', 'Passion', 'Action', 'Courage'],
      description: 'A knight charges forward, driven by passion and adventure.',
      advice: 'Channel your energy into bold, purposeful action.',
    },
    {
      name: 'Queen of Wands',
      number: 13,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Confidence, charisma, and leadership.',
      reversedMeaning: 'Jealousy, insecurity, or demanding behavior.',
      symbolism: ['Sunflower: Vitality', 'Wand: Power', 'Throne: Authority'],
      numerology: '13 signifies transformation and leadership.',
      keywords: ['Confidence', 'Charisma', 'Leadership', 'Energy'],
      description: 'The Queen holds a wand, radiating warmth and leadership.',
      advice: 'Embrace your inner strength and inspire others.',
    },
    {
      name: 'King of Wands',
      number: 14,
      arcana: 'Minor',
      suit: 'Wands',
      uprightMeaning: 'Vision, leadership, and bold decision-making.',
      reversedMeaning: 'Domineering, impulsiveness, or lack of vision.',
      symbolism: ['Salamander: Resilience', 'Wand: Authority', 'Throne: Leadership'],
      numerology: '14 represents balance and vision.',
      keywords: ['Leadership', 'Vision', 'Authority', 'Inspiration'],
      description: 'The King holds a wand, embodying visionary leadership.',
      advice: 'Lead with confidence and inspire others with your vision.',
    },
    // Minor Arcana: Cups
    {
      name: 'Ace of Cups',
      number: 1,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Emotional new beginnings, love, and compassion.',
      reversedMeaning: 'Blocked emotions, overwhelm, or repressed feelings.',
      symbolism: ['Cup: Emotions', 'Dove: Peace', 'Water: Intuition'],
      numerology: '1 signifies new starts and emotional potential.',
      keywords: ['Love', 'Compassion', 'Intuition', 'Creativity'],
      description: 'A hand holds an overflowing cup, symbolizing emotional abundance.',
      advice: 'Open your heart to love and emotional connections.',
    },
    {
      name: 'Two of Cups',
      number: 2,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Partnership, love, and mutual connection.',
      reversedMeaning: 'Disharmony, breakup, or imbalance in relationships.',
      symbolism: ['Cups: Exchange', 'Caduceus: Harmony', 'Couple: Union'],
      numerology: '2 represents partnership and balance.',
      keywords: ['Love', 'Partnership', 'Harmony', 'Connection'],
      description: 'Two figures exchange cups, symbolizing mutual love and respect.',
      advice: 'Nurture relationships through mutual understanding.',
    },
    {
      name: 'Three of Cups',
      number: 3,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Celebration, friendship, and community.',
      reversedMeaning: 'Overindulgence, isolation, or gossip.',
      symbolism: ['Cups: Joy', 'Dance: Celebration', 'Fruit: Abundance'],
      numerology: '3 symbolizes joy and creativity.',
      keywords: ['Friendship', 'Celebration', 'Community', 'Joy'],
      description: 'Three figures dance, celebrating friendship and joy.',
      advice: 'Celebrate with loved ones and cherish community.',
    },
    {
      name: 'Four of Cups',
      number: 4,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Apathy, contemplation, or missed opportunities.',
      reversedMeaning: 'New interest, motivation, or seizing opportunities.',
      symbolism: ['Cups: Choices', 'Tree: Stability', 'Figure: Contemplation'],
      numerology: '4 represents stability and introspection.',
      keywords: ['Apathy', 'Contemplation', 'Opportunity', 'Reevaluation'],
      description: 'A figure ignores a cup, lost in thought and missing opportunities.',
      advice: 'Reflect on your emotions but stay open to new possibilities.',
    },
    {
      name: 'Five of Cups',
      number: 5,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Loss, regret, or focusing on the negative.',
      reversedMeaning: 'Acceptance, moving on, or finding hope.',
      symbolism: ['Spilled Cups: Loss', 'Bridge: Hope', 'Figure: Grief'],
      numerology: '5 signifies change and emotional challenges.',
      keywords: ['Loss', 'Regret', 'Grief', 'Hope'],
      description: 'A figure mourns spilled cups, overlooking hope in the distance.',
      advice: 'Acknowledge loss but focus on what remains.',
    },
    {
      name: 'Six of Cups',
      number: 6,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Nostalgia, childhood memories, or kindness.',
      reversedMeaning: 'Living in the past, immaturity, or stuck emotions.',
      symbolism: ['Cups: Gifts', 'Children: Innocence', 'Flowers: Memories'],
      numerology: '6 represents harmony and nostalgia.',
      keywords: ['Nostalgia', 'Memories', 'Kindness', 'Innocence'],
      description: 'Children exchange cups, evoking memories and kindness.',
      advice: 'Cherish memories but live in the present.',
    },
    {
      name: 'Seven of Cups',
      number: 7,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Choices, fantasies, or illusions.',
      reversedMeaning: 'Clarity, focus, or realistic decisions.',
      symbolism: ['Cups: Options', 'Clouds: Illusions', 'Figure: Dreaming'],
      numerology: '7 symbolizes imagination and choices.',
      keywords: ['Choices', 'Fantasies', 'Illusions', 'Decisions'],
      description: 'A figure faces cups filled with dreams, symbolizing choices.',
      advice: 'Weigh your options carefully to avoid illusions.',
    },
    {
      name: 'Eight of Cups',
      number: 8,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Walking away, seeking purpose, or emotional growth.',
      reversedMeaning: 'Fear of change, stagnation, or clinging to the past.',
      symbolism: ['Cups: Abandonment', 'Moon: Intuition', 'Path: Journey'],
      numerology: '8 represents transition and growth.',
      keywords: ['Departure', 'Search', 'Growth', 'Change'],
      description: 'A figure leaves cups behind, seeking deeper meaning.',
      advice: 'Let go of what no longer serves you and seek your truth.',
    },
    {
      name: 'Nine of Cups',
      number: 9,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Contentment, satisfaction, and wishes fulfilled.',
      reversedMeaning: 'Greed, dissatisfaction, or unfulfilled desires.',
      symbolism: ['Cups: Abundance', 'Figure: Satisfaction', 'Table: Stability'],
      numerology: '9 signifies fulfillment and completion.',
      keywords: ['Contentment', 'Satisfaction', 'Wishes', 'Abundance'],
      description: 'A figure sits contentedly before cups, symbolizing fulfillment.',
      advice: 'Appreciate what you have and share your abundance.',
    },
    {
      name: 'Ten of Cups',
      number: 10,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Harmony, family, and emotional fulfillment.',
      reversedMeaning: 'Disharmony, family conflict, or disconnection.',
      symbolism: ['Rainbow: Joy', 'Family: Unity', 'Cups: Fulfillment'],
      numerology: '10 represents completion and harmony.',
      keywords: ['Harmony', 'Family', 'Fulfillment', 'Joy'],
      description: 'A family celebrates under a rainbow, symbolizing emotional bliss.',
      advice: 'Cherish loved ones and cultivate harmony.',
    },
    {
      name: 'Page of Cups',
      number: 11,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Creativity, emotional messages, or intuition.',
      reversedMeaning: 'Emotional immaturity, insecurity, or blocked creativity.',
      symbolism: ['Cup: Emotion', 'Fish: Intuition', 'Page: Youthful energy'],
      numerology: '11 signifies intuition and sensitivity.',
      keywords: ['Creativity', 'Intuition', 'Messages', 'Sensitivity'],
      description: 'A page holds a cup with a fish, symbolizing emotional curiosity.',
      advice: 'Listen to your emotions and explore your creativity.',
    },
    {
      name: 'Knight of Cups',
      number: 12,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Romance, idealism, and following your heart.',
      reversedMeaning: 'Moodiness, unrealistic dreams, or emotional manipulation.',
      symbolism: ['Cup: Love', 'Horse: Pursuit', 'Knight: Idealism'],
      numerology: '12 represents emotional pursuit and creativity.',
      keywords: ['Romance', 'Idealism', 'Emotion', 'Charm'],
      description: 'A knight offers a cup, driven by romantic and emotional ideals.',
      advice: 'Follow your heart but stay grounded in reality.',
    },
    {
      name: 'Queen of Cups',
      number: 13,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Compassion, intuition, and emotional support.',
      reversedMeaning: 'Emotional overwhelm, co-dependency, or moodiness.',
      symbolism: ['Cup: Intuition', 'Throne: Authority', 'Water: Emotions'],
      numerology: '13 signifies emotional depth and transformation.',
      keywords: ['Compassion', 'Intuition', 'Support', 'Empathy'],
      description: 'The Queen gazes at a cup, embodying emotional wisdom.',
      advice: 'Offer compassion and trust your intuitive insights.',
    },
    {
      name: 'King of Cups',
      number: 14,
      arcana: 'Minor',
      suit: 'Cups',
      uprightMeaning: 'Emotional balance, compassion, and wisdom.',
      reversedMeaning: 'Emotional manipulation, volatility, or detachment.',
      symbolism: ['Cup: Wisdom', 'Throne: Stability', 'Sea: Emotions'],
      numerology: '14 represents balance and emotional maturity.',
      keywords: ['Compassion', 'Balance', 'Wisdom', 'Control'],
      description: 'The King sits calmly, mastering his emotions with wisdom.',
      advice: 'Balance your emotions and lead with compassion.',
    },
    // Minor Arcana: Swords
    {
      name: 'Ace of Swords',
      number: 1,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Clarity, truth, and mental breakthrough.',
      reversedMeaning: 'Confusion, miscommunication, or clouded judgment.',
      symbolism: ['Sword: Truth', 'Crown: Victory', 'Clouds: Clarity'],
      numerology: '1 signifies new ideas and clarity.',
      keywords: ['Clarity', 'Truth', 'Breakthrough', 'Intellect'],
      description: 'A hand holds a sword, symbolizing mental clarity and truth.',
      advice: 'Seek truth and use logic to cut through confusion.',
    },
    {
      name: 'Two of Swords',
      number: 2,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Indecision, stalemate, or emotional detachment.',
      reversedMeaning: 'Clarity, decision-making, or emotional release.',
      symbolism: ['Blindfold: Indecision', 'Swords: Balance', 'Water: Emotions'],
      numerology: '2 represents choices and duality.',
      keywords: ['Indecision', 'Stalemate', 'Balance', 'Choice'],
      description: 'A blindfolded figure holds two swords, symbolizing indecision.',
      advice: 'Face your choices and seek clarity to move forward.',
    },
    {
      name: 'Three of Swords',
      number: 3,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Heartbreak, betrayal, or emotional pain.',
      reversedMeaning: 'Healing, forgiveness, or moving on.',
      symbolism: ['Heart: Pain', 'Swords: Betrayal', 'Rain: Grief'],
      numerology: '3 symbolizes emotional expression and pain.',
      keywords: ['Heartbreak', 'Betrayal', 'Pain', 'Grief'],
      description: 'A heart pierced by swords, representing emotional pain.',
      advice: 'Acknowledge your pain and begin the healing process.',
    },
    {
      name: 'Four of Swords',
      number: 4,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Rest, recovery, and mental recharge.',
      reversedMeaning: 'Burnout, restlessness, or delayed recovery.',
      symbolism: ['Tomb: Rest', 'Swords: Stillness', 'Church: Peace'],
      numerology: '4 represents stability and recovery.',
      keywords: ['Rest', 'Recovery', 'Peace', 'Reflection'],
      description: 'A figure rests in a tomb, symbolizing a need for mental peace.',
      advice: 'Take time to rest and recharge your mind.',
    },
    {
      name: 'Five of Swords',
      number: 5,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Conflict, betrayal, or winning at a cost.',
      reversedMeaning: 'Reconciliation, regret, or moving past conflict.',
      symbolism: ['Swords: Conflict', 'Figures: Defeat', 'Sky: Tension'],
      numerology: '5 signifies conflict and change.',
      keywords: ['Conflict', 'Betrayal', 'Victory', 'Loss'],
      description: 'A figure holds swords, symbolizing a hollow victory.',
      advice: 'Choose your battles wisely and seek fair resolutions.',
    },
    {
      name: 'Six of Swords',
      number: 6,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Transition, moving on, or healing journey.',
      reversedMeaning: 'Stagnation, resistance, or unresolved issues.',
      symbolism: ['Boat: Transition', 'Swords: Burdens', 'Water: Healing'],
      numerology: '6 represents harmony and transition.',
      keywords: ['Transition', 'Healing', 'Journey', 'Movement'],
      description: 'A boat carries figures to calmer waters, symbolizing healing.',
      advice: 'Move forward and leave past struggles behind.',
    },
    {
      name: 'Seven of Swords',
      number: 7,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Deception, strategy, or cunning.',
      reversedMeaning: 'Honesty, regret, or consequences of deceit.',
      symbolism: ['Swords: Deception', 'Figure: Stealth', 'Camp: Strategy'],
      numerology: '7 symbolizes strategy and cunning.',
      keywords: ['Deception', 'Strategy', 'Cunning', 'Stealth'],
      description: 'A figure sneaks away with swords, symbolizing cunning.',
      advice: 'Be honest and consider the consequences of your actions.',
    },
    {
      name: 'Eight of Swords',
      number: 8,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Restriction, feeling trapped, or self-imposed limitations.',
      reversedMeaning: 'Freedom, empowerment, or breaking free.',
      symbolism: ['Blindfold: Limitation', 'Swords: Restriction', 'Water: Emotions'],
      numerology: '8 represents restriction and liberation.',
      keywords: ['Restriction', 'Trapped', 'Fear', 'Limitation'],
      description: 'A bound figure is surrounded by swords, feeling trapped.',
      advice: 'Recognize your power to break free from limitations.',
    },
    {
      name: 'Nine of Swords',
      number: 9,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Anxiety, despair, or nightmares.',
      reversedMeaning: 'Hope, recovery, or facing fears.',
      symbolism: ['Swords: Fear', 'Bed: Nightmares', 'Figure: Despair'],
      numerology: '9 signifies intense emotions and nearing resolution.',
      keywords: ['Anxiety', 'Despair', 'Fear', 'Nightmares'],
      description: 'A figure sits up in bed, overwhelmed by worry and fear.',
      advice: 'Confront your fears and seek support to find peace.',
    },
    {
      name: 'Ten of Swords',
      number: 10,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Betrayal, rock bottom, or painful endings.',
      reversedMeaning: 'Recovery, acceptance, or new beginnings.',
      symbolism: ['Swords: Betrayal', 'Figure: Defeat', 'Sunrise: Hope'],
      numerology: '10 represents endings and new beginnings.',
      keywords: ['Betrayal', 'Endings', 'Defeat', 'Recovery'],
      description: 'A figure lies pierced by swords, symbolizing a painful ending.',
      advice: 'Accept the ending and look for new beginnings.',
    },
    {
      name: 'Page of Swords',
      number: 11,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Curiosity, new ideas, or mental agility.',
      reversedMeaning: 'Gossip, impulsiveness, or scattered thoughts.',
      symbolism: ['Sword: Intellect', 'Wind: Change', 'Page: Curiosity'],
      numerology: '11 signifies intuition and new ideas.',
      keywords: ['Curiosity', 'Intellect', 'Ideas', 'Vigilance'],
      description: 'A page holds a sword, eager to explore new ideas.',
      advice: 'Stay curious but avoid hasty judgments.',
    },
    {
      name: 'Knight of Swords',
      number: 12,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Ambition, action, and mental clarity.',
      reversedMeaning: 'Recklessness, aggression, or impulsiveness.',
      symbolism: ['Sword: Action', 'Horse: Speed', 'Knight: Determination'],
      numerology: '12 represents dynamic intellect and pursuit.',
      keywords: ['Ambition', 'Action', 'Clarity', 'Determination'],
      description: 'A knight charges with a sword, driven by intellect and ambition.',
      advice: 'Pursue your goals with clarity but avoid recklessness.',
    },
    {
      name: 'Queen of Swords',
      number: 13,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Clarity, independence, and sharp intellect.',
      reversedMeaning: 'Coldness, bitterness, or clouded judgment.',
      symbolism: ['Sword: Truth', 'Throne: Authority', 'Clouds: Clarity'],
      numerology: '13 signifies transformation and intellect.',
      keywords: ['Clarity', 'Independence', 'Intellect', 'Truth'],
      description: 'The Queen holds a sword, embodying clear thinking and independence.',
      advice: 'Speak your truth and maintain your independence.',
    },
    {
      name: 'King of Swords',
      number: 14,
      arcana: 'Minor',
      suit: 'Swords',
      uprightMeaning: 'Authority, truth, and intellectual leadership.',
      reversedMeaning: 'Manipulation, harshness, or abuse of power.',
      symbolism: ['Sword: Authority', 'Throne: Power', 'Clouds: Clarity'],
      numerology: '14 represents balance and intellectual mastery.',
      keywords: ['Authority', 'Truth', 'Intellect', 'Leadership'],
      description: 'The King wields a sword, symbolizing intellectual authority.',
      advice: 'Lead with logic and uphold truth in your decisions.',
    },
    // Minor Arcana: Pentacles
    {
      name: 'Ace of Pentacles',
      number: 1,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'New opportunities, prosperity, and material growth.',
      reversedMeaning: 'Missed opportunities, financial loss, or instability.',
      symbolism: ['Pentacle: Wealth', 'Hand: Opportunity', 'Garden: Growth'],
      numerology: '1 signifies new beginnings and potential.',
      keywords: ['Prosperity', 'Opportunity', 'Wealth', 'Growth'],
      description: 'A hand offers a pentacle, symbolizing material opportunities.',
      advice: 'Seize new financial or career opportunities.',
    },
    {
      name: 'Two of Pentacles',
      number: 2,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Balance, adaptability, and multitasking.',
      reversedMeaning: 'Imbalance, overwhelm, or poor prioritization.',
      symbolism: ['Pentacles: Balance', 'Infinity Symbol: Flow', 'Ships: Adaptability'],
      numerology: '2 represents balance and adaptability.',
      keywords: ['Balance', 'Adaptability', 'Multitasking', 'Flexibility'],
      description: 'A figure juggles pentacles, symbolizing balance and adaptability.',
      advice: 'Prioritize and stay flexible to maintain balance.',
    },
    {
      name: 'Three of Pentacles',
      number: 3,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Collaboration, craftsmanship, and teamwork.',
      reversedMeaning: 'Lack of teamwork, poor quality, or disharmony.',
      symbolism: ['Pentacles: Work', 'Church: Craftsmanship', 'Figures: Collaboration'],
      numerology: '3 symbolizes creativity and teamwork.',
      keywords: ['Collaboration', 'Craftsmanship', 'Teamwork', 'Skill'],
      description: 'Artisans work together, symbolizing skill and collaboration.',
      advice: 'Work with others to achieve high-quality results.',
    },
    {
      name: 'Four of Pentacles',
      number: 4,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Security, control, or holding onto resources.',
      reversedMeaning: 'Greed, materialism, or financial insecurity.',
      symbolism: ['Pentacles: Wealth', 'Figure: Control', 'City: Stability'],
      numerology: '4 represents stability and security.',
      keywords: ['Security', 'Control', 'Wealth', 'Stability'],
      description: 'A figure clutches pentacles, symbolizing control over resources.',
      advice: 'Balance security with generosity to avoid stagnation.',
    },
    {
      name: 'Five of Pentacles',
      number: 5,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Poverty, hardship, or feeling excluded.',
      reversedMeaning: 'Recovery, hope, or spiritual wealth.',
      symbolism: ['Pentacles: Loss', 'Church: Hope', 'Snow: Hardship'],
      numerology: '5 signifies change and struggle.',
      keywords: ['Poverty', 'Hardship', 'Exclusion', 'Hope'],
      description: 'Figures walk in snow, symbolizing financial or emotional struggle.',
      advice: 'Seek support and focus on inner strength during hardship.',
    },
    {
      name: 'Six of Pentacles',
      number: 6,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Generosity, charity, or balanced giving.',
      reversedMeaning: 'Selfishness, debt, or unequal exchange.',
      symbolism: ['Pentacles: Wealth', 'Scales: Balance', 'Figures: Giving'],
      numerology: '6 represents harmony and generosity.',
      keywords: ['Generosity', 'Charity', 'Balance', 'Sharing'],
      description: 'A figure gives coins, symbolizing balanced generosity.',
      advice: 'Give and receive with fairness and gratitude.',
    },
    {
      name: 'Seven of Pentacles',
      number: 7,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Patience, investment, or long-term rewards.',
      reversedMeaning: 'Impatience, lack of progress, or wasted effort.',
      symbolism: ['Pentacles: Growth', 'Plants: Investment', 'Figure: Patience'],
      numerology: '7 symbolizes effort and evaluation.',
      keywords: ['Patience', 'Investment', 'Rewards', 'Effort'],
      description: 'A figure assesses growing plants, symbolizing patience.',
      advice: 'Stay patient and trust in your long-term efforts.',
    },
    {
      name: 'Eight of Pentacles',
      number: 8,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Hard work, skill development, or dedication.',
      reversedMeaning: 'Lack of focus, poor quality, or burnout.',
      symbolism: ['Pentacles: Work', 'Tools: Craftsmanship', 'Figure: Dedication'],
      numerology: '8 represents effort and mastery.',
      keywords: ['Hard Work', 'Skill', 'Dedication', 'Craftsmanship'],
      description: 'A worker crafts pentacles, symbolizing dedication to skill.',
      advice: 'Focus on improving your skills through consistent effort.',
    },
    {
      name: 'Nine of Pentacles',
      number: 9,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Abundance, independence, or self-sufficiency.',
      reversedMeaning: 'Financial dependence, isolation, or materialism.',
      symbolism: ['Pentacles: Wealth', 'Garden: Abundance', 'Falcon: Control'],
      numerology: '9 signifies fulfillment and independence.',
      keywords: ['Abundance', 'Independence', 'Luxury', 'Success'],
      description: 'A figure enjoys a lush garden, symbolizing self-sufficiency.',
      advice: 'Enjoy your achievements and maintain independence.',
    },
    {
      name: 'Ten of Pentacles',
      number: 10,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Wealth, legacy, or family stability.',
      reversedMeaning: 'Financial loss, family disputes, or instability.',
      symbolism: ['Pentacles: Wealth', 'Family: Legacy', 'Arch: Stability'],
      numerology: '10 represents completion and legacy.',
      keywords: ['Wealth', 'Legacy', 'Family', 'Stability'],
      description: 'A family enjoys wealth, symbolizing legacy and stability.',
      advice: 'Build a lasting legacy and cherish family connections.',
    },
    {
      name: 'Page of Pentacles',
      number: 11,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Ambition, learning, or new opportunities.',
      reversedMeaning: 'Procrastination, lack of focus, or missed opportunities.',
      symbolism: ['Pentacle: Opportunity', 'Fields: Growth', 'Page: Ambition'],
      numerology: '11 signifies new beginnings and ambition.',
      keywords: ['Ambition', 'Learning', 'Opportunity', 'Focus'],
      description: 'A page studies a pentacle, symbolizing ambition and learning.',
      advice: 'Stay focused and seize new learning opportunities.',
    },
    {
      name: 'Knight of Pentacles',
      number: 12,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Hard work, reliability, or steady progress.',
      reversedMeaning: 'Stagnation, laziness, or lack of progress.',
      symbolism: ['Pentacle: Duty', 'Horse: Stability', 'Knight: Reliability'],
      numerology: '12 represents steady effort and responsibility.',
      keywords: ['Hard Work', 'Reliability', 'Progress', 'Duty'],
      description: 'A knight holds a pentacle, symbolizing steady work and reliability.',
      advice: 'Stay committed and work steadily toward your goals.',
    },
    {
      name: 'Queen of Pentacles',
      number: 13,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Nurturing, practicality, or financial security.',
      reversedMeaning: 'Neglect, financial insecurity, or imbalance.',
      symbolism: ['Pentacle: Wealth', 'Throne: Stability', 'Nature: Nurturing'],
      numerology: '13 signifies transformation and nurturing.',
      keywords: ['Nurturing', 'Practicality', 'Security', 'Abundance'],
      description: 'The Queen holds a pentacle, embodying nurturing and security.',
      advice: 'Care for yourself and others while maintaining practicality.',
    },
    {
      name: 'King of Pentacles',
      number: 14,
      arcana: 'Minor',
      suit: 'Pentacles',
      uprightMeaning: 'Wealth, leadership, or practical success.',
      reversedMeaning: 'Greed, stubbornness, or financial mismanagement.',
      symbolism: ['Pentacle: Wealth', 'Throne: Authority', 'Garden: Success'],
      numerology: '14 represents stability and leadership.',
      keywords: ['Wealth', 'Leadership', 'Success', 'Stability'],
      description: 'The King holds a pentacle, symbolizing wealth and leadership.',
      advice: 'Lead with practicality and build lasting success.',
    },
  ];
const seedTarotCards = async () => {
  const count = await TarotCard.countDocuments();
  if (count === 0) {
    console.log("🌱 Seeding tarot database...");
    await TarotCard.insertMany(cards);
    console.log("✅ Tarot cards seeded.");
  } else {
    console.log("📦 Tarot cards already exist.");
  }
};

// Seed database on startup

seedTarotCards().catch((err) => console.error('Error seeding database:', err));

// API Routes

app.get('/api/tarot', async (req, res) => {
  try {
    const cards = await TarotCard.find();
    res.json(cards);
  } catch (err) {
    res.status(500).json({ message: 'Error fetching tarot cards', error: err.message });
  }
});

app.get('/api/tarot/:name', async (req, res) => {
  try {
    const card = await TarotCard.findOne({ name: req.params.name });
    if (!card) return res.status(404).json({ message: 'Card not found' });
    res.json(card);
  } catch (err) {
    res.status(500).json({ message: 'Error fetching tarot card', error: err.message });
  }
});

// Random card endpoint
app.get('/api/tarot/random', async (req, res) => {
  try {
    const cards = await TarotCard.find();
    console.log('🎴 Total cards in DB:', cards.length);

    if (!cards.length) {
      console.log('⚠️ No cards found.');
      return res.status(404).json({ message: 'No cards found in database' });
    }

    const randomCard = cards[Math.floor(Math.random() * cards.length)];
    console.log('🔮 Selected card:', randomCard.name);
    res.json(randomCard);
  } catch (err) {
    console.error('❌ Error fetching random card:', err.message);
    res.status(500).json({ message: 'Error fetching random card', error: err.message });
  }
});



// Start Server
const PORT = process.env.PORT || 5000;

  // ✅ Log registered routes *after* server starts
 app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);

  if (app._router && app._router.stack) {
    console.log('\n📍 Registered Routes:');
    app._router.stack
      .filter(r => r.route)
      .forEach(r => {
        const method = r.route.stack[0].method.toUpperCase();
        console.log(`📍 ${method} ${r.route.path}`);
      });
  } else {
    console.log('⚠️ Cannot print routes — app._router is not initialized yet.');
  }
});

